// Predefined neighbourhoods for the MVP
export const NEIGHBOURHOODS = [
  'Abbottsfield',
  'Albany',
  'Alberta Avenue',
  'Alberta Park Industrial',
  'Alces',
  'Aldergrove',
  'Allard',
  'Allendale',
  'Ambleside',
  'Anthony Henday',
  'Anthony Henday Big Lake',
  'Anthony Henday Castledowns',
  'Anthony Henday Clareview',
  'Anthony Henday Energy Park',
  'Anthony Henday Horse Hill',
  'Anthony Henday Lake District',
  'Anthony Henday Mistatim',
  'Anthony Henday Rampart',
  'Anthony Henday South',
  'Anthony Henday South Blackburne',
  'Anthony Henday South East',
  'Anthony Henday South West',
  'Anthony Henday Terwillegar',
  'Argyll',
  'Armstrong Industrial',
  'Aspen Gardens',
  'Aster',
  'Athlone',
  'Avonmore',
  'Balwin',
  'Bannerman',
  'Baranow',
  'Baturyn',
  'Beacon Heights',
  'Bearspaw',
  'Beaumaris',
  'Belgravia',
  'Belle Rive',
  'Bellevue',
  'Belmead',
  'Belmont',
  'Belvedere',
  'Bergman',
  'Beverly Heights',
  'Bisset',
  'Blackburne',
  'Blackmud Creek',
  'Blackmud Creek Ravine',
  'Blatchford Area',
  'Blue Quill',
  'Blue Quill Estates',
  'Bonaventure Industrial',
  'Bonnie Doon',
  'Boyle Street',
  'Brander Gardens',
  'Breckenridge Greens',
  'Brintnell',
  'Britannia Youngstown',
  'Brookside',
  'Brown Industrial',
  'Bulyea Heights',
  'Caernarvon',
  'Calder',
  'Calgary Trail North',
  'Calgary Trail South',
  'Callaghan',
  'Callingwood North',
  'Callingwood South',
  'Cameron Heights',
  'Canon Ridge',
  'Canora',
  'Canossa',
  'Capilano',
  'Carleton Square Industrial',
  'Carlisle',
  'Carlton',
  'Carter Crest',
  'Cashman',
  'Casselman',
  'Cavanagh',
  'Central McDougall',
  'Chambery',
  'Chappelle Area',
  'Charlesworth',
  'Clareview Town Centre',
  'Clover Bar Area',
  'Cloverdale',
  'Coronet Addition Industrial',
  'Coronet Industrial',
  'CPR Irvine',
  'Crawford Plains',
  'Crestwood',
  'Cromdale',
  'Crossroads',
  'Crystallina Nera East',
  'Crystallina Nera West',
  'Cumberland',
  'Cy Becker',
  'Daly Grove',
  'Davies Industrial East',
  'Davies Industrial West',
  'Dechene',
  'Decoteau',
  'Delton',
  'Delwood',
  'Desrochers Area',
  'Dominion Industrial',
  'Donsdale',
  'Dovercourt',
  'Downtown',
  'Duggan',
  'Dunluce',
  'Eastgate Business Park',
  'Eastwood',
  'Eaux Claires',
  'Ebbers',
  'Edgemont',
  'Edmiston Industrial',
  'Edmonton Energy And Technology Park',
  'Edmonton Northlands',
  'Edmonton Research and Development Park',
  'Edmonton South Central',
  'Edmonton South Central East',
  'Edmonton South East',
  'Edmonton South West',
  'Ekota',
  'Ellerslie',
  'Ellerslie Industrial',
  'Elmwood',
  'Elmwood Park',
  'Elsinore',
  'Empire Park',
  'Ermineskin',
  'Evansdale',
  'Evergreen',
  'Falconer Heights',
  'Forest Heights',
  'Fraser',
  'Fulton Place',
  'Gagnon Estate Industrial',
  'Gainer Industrial',
  'Gariepy',
  'Garneau',
  'Garside Industrial',
  'Girard Industrial',
  'Glastonbury',
  'Glengarry',
  'Glenora',
  'Glenridding Heights',
  'Glenridding Ravine',
  'Glenwood',
  'Gold Bar',
  'Goodridge Corners',
  'Gorman',
  'Grandview Heights',
  'Granville',
  'Graydon Hill',
  'Greenfield',
  'Greenview',
  'Griesbach',
  'Grovenor',
  'Haddow',
  'Hagmann Estate Industrial',
  'Hairsine',
  'Hawin Park Estate Industrial',
  'Hawks Ridge',
  'Hays Ridge Area',
  'Hazeldean',
  'Henderson Estates',
  'Heritage Valley Area',
  'Heritage Valley Town Centre',
  'Highlands',
  'High Park',
  'High Park Industrial',
  'Hillview',
  'Hodgson',
  'Hollick-Kenyon',
  'Holyrood',
  'Homesteader',
  'Hudson',
  'Huff Bremner Estate Industrial',
  'Idylwylde',
  'Industrial Heights',
  'Inglewood',
  'Jackson Heights',
  'Jamieson Place',
  'Jasper Park',
  'Kameyosek',
  'Keheewin',
  'Kendal',
  'Kenilworth',
  'Kennedale Industrial',
  'Kensington',
  'Kernohan',
  'Keswick',
  'Kildare',
  'Kilkenny',
  'Killarney',
  'King Edward Park',
  'Kinglet Gardens',
  'Kiniski Gardens',
  'Kinokamau Plains Area',
  'Kirkness',
  'Klarvatten',
  'Lago Lindo',
  'Lambton Industrial',
  'Lansdowne',
  'La Perle',
  'Larkspur',
  'Lauderdale',
  'Laurel',
  'Laurier Heights',
  'Lee Ridge',
  'Leger',
  'Lendrum Place',
  'Lewis Farms',
  'Lewis Farms Business Employment',
  'Lorelei',
  'Lymburn',
  'Lynnwood',
  'MacEwan',
  'Mactaggart',
  'Magrath Heights',
  'Malmo Plains',
  'Maple',
  'Maple Ridge',
  'Maple Ridge Industrial',
  'Marquis',
  'Matt Berry',
  'Mattson',
  'Mayfield',
  'Mayliewan',
  'McArthur Industrial',
  'McCauley',
  'McConachie',
  'McIntyre Industrial',
  'McKernan',
  'McLeod',
  'McNamara Industrial',
  'McQueen',
  'Meadowlark Park',
  'Meltwater',
  'Menisa',
  'Meyokumin',
  'Meyonohk',
  'Michaels Park',
  'Mill Creek Ravine North',
  'Mill Creek Ravine South',
  'Miller',
  'Mill Woods Golf Course',
  'Mill Woods Park',
  'Mill Woods Town Centre',
  'Minchau',
  'Mistatim Industrial',
  'Mitchell Industrial',
  'Montrose',
  'Morin Industrial',
  'Morris Industrial',
  'Newton',
  'North Glenora',
  'Northmount',
  'Norwester Industrial',
  'Ogilvie Ridge',
  'Oleskiw',
  'Ormsby Place',
  'Ottewell',
  'Overlanders',
  'Oxford',
  'Ozerna',
  'Paisley',
  'Papaschase Industrial',
  'Parkallen',
  'Parkdale',
  'Parkview',
  'Parsons Industrial',
  'Patricia Heights',
  'Pembina',
  'Pintail Landing',
  'Place LaRue',
  'Pleasantview',
  'Pollard Meadows',
  'Potter Greens',
  'Poundmaker Industrial',
  'Prince Charles',
  'Prince Rupert',
  'Pylypow Industrial',
  'Quarry Ridge',
  'Queen Alexandra',
  'Queen Mary Park',
  'Quesnell Heights',
  'Rampart Industrial',
  'Ramsay Heights',
  'Rapperswill',
  'Rhatigan Ridge',
  'Richfield',
  'Richford',
  'Rideau Park',
  'Rio Terrace',
  'Ritchie',
  'Riverdale',
  "River's Edge",
  'River Valley Cameron',
  'River Valley Capitol Hill',
  'River Valley Fort Edmonton',
  'River Valley Glenora',
  'River Valley Gold Bar',
  'River Valley Hermitage',
  'River Valley Highlands',
  'River Valley Kendal',
  'River Valley Keswick',
  'River Valley Kinnaird',
  'River Valley Laurier',
  'River Valley Lessard North',
  'River Valley Mayfair',
  'River Valley Oleskiw',
  'River Valley Riverside',
  'River Valley Rundle',
  'River Valley Terwillegar',
  'River Valley Victoria',
  'River Valley Walterdale',
  'River Valley Whitemud',
  'River Valley Windermere',
  'Riverview Area',
  'Roper Industrial',
  'Rosedale Industrial',
  'Rosenthal',
  'Rossdale',
  'Rosslyn',
  'Royal Gardens',
  'Rundle Heights',
  'Rural North East Horse Hill',
  'Rural North East South Sturgeon',
  'Rutherford',
  'Sakaw',
  'Satoo',
  'Schonsee',
  'Secord',
  'Sheffield Industrial',
  'Sherbrooke',
  'Sherwood',
  'Sifton Park',
  'Silver Berry',
  'Skyrattler',
  'Southeast Industrial',
  'South Edmonton Common',
  'South Terwillegar',
  'Spruce Avenue',
  'Starling',
  'Steinhauer',
  'Stewart Greens',
  'Stillwater',
  'Stone Industrial',
  'Strathcona',
  'Strathcona Industrial Park',
  'Strathcona Junction',
  'Strathearn',
  'Suder Greens',
  'Summerlea',
  'Summerside',
  'Sunwapta Industrial',
  'Sweet Grass',
  'Tamarack',
  'Tawa',
  'Terrace Heights',
  'Terra Losa',
  'Terwillegar Towne',
  'The Hamptons',
  'The Orchards At Ellerslie',
  'The Uplands',
  'Thorncliff',
  'Tipaskan',
  'Trumpeter Area',
  'Tweddle Place',
  'Twin Brooks',
  'University of Alberta',
  'University of Alberta Farm',
  'Virginia Park',
  'Walker',
  'Webber Greens',
  'Wedgewood Heights',
  'Weinlos',
  'Weir Industrial',
  'Wellington',
  'Westbrook Estates',
  'West Jasper Place',
  'West Meadowlark Park',
  'Westmount',
  'Westridge',
  'West Sheffield Industrial',
  'Westview Village',
  'Westwood',
  'White Industrial',
  'Whitemud Creek Ravine North',
  'Whitemud Creek Ravine South',
  'Whitemud Creek Ravine Twin Brooks',
  'Wihkwentowin',
  'Wild Rose',
  'Wilson Industrial',
  'Windermere',
  'Windsor Park',
  'Winterburn Industrial Area East',
  'Winterburn Industrial Area West',
  'Woodcroft',
  'Yellowhead Corridor East',
  'Yellowhead Corridor West',
  'York',
  'Youngstown Industrial',
]

// Coat colour options
export const COAT_COLOURS = [
  'Black',
  'White',
  'Orange',
  'Grey',
  'Tabby',
  'Tortoiseshell',
  'Calico',
  'Bi-colour',
  'Other',
]

// Health status options
export const HEALTH_STATUS = [
  'Healthy',
  'Minor injury',
  'Looks unwell',
  'Unknown',
]

// Temperament options
export const TEMPERAMENT = [
  'Friendly',
  'Shy',
  'Feral',
  'Unknown',
]

// Cat status options
export const CAT_STATUS = {
  PET: 'pet',
  COMMUNITY_CAT: 'community_cat',
  UNKNOWN: 'unknown',
}

// API endpoints
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'
